hdb_dbt:
  outputs:
    dev:
      dataset: hdb_analytics_marts   #   testing - see this is bigquery dataset: hdb_raw_data
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile:  /home/taijl/DSAI/S2_BigData/DSAI_HDB_Project/project-8d552288-1acb-4a23-893-07fe8627d11f.json
      location: US
      method: service-account
      priority: interactive
      project: project-8d552288-1acb-4a23-893
      threads: 1
      type: bigquery
  target: dev